//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Credits { get; set; }
        public string ClassHoursPerWeek { get; set; }
        public string StartDate { get; set; }
        public string NumOfWeeks { get; set; }
        public string HoursWorked { get; set; }
        public string EndDate { get; set; }
        public int SelfStudyHours { get; set; }
        public int RemainingHours { get; set; }

        // Foreign key to reference the Identity User Id
        public string UserId { get; set; }
        
    }
   
}
